### ISSUE TITLE
Please update README with dependencies and project setup steps

### ISSUE THREAD

**Issue by sandipsahoo2k2** [benorama/ngrx-realtime-app#2]
I liked the prototype I took this example and tried to run in my system .. I have almost ended up enitre saturday fixing the dependencies with ngrx  still unsolved . Could have used just the eventBusservice without ngrx I wish

**Comment by benorama** [comment]
Hi @sandipsahoo2k2 ,

I was able to successfully git clone and run both client and server by following the current README file.

Please feel free to re-open the issue with more details, thanks.
